//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDERSHANE.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLADMİN
    {
        public int İD { get; set; }
        public string kulanici { get; set; }
        public string sifre { get; set; }
    }
}
