//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDERSHANE.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLBOLUM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLBOLUM()
        {
            this.TBLODEV = new HashSet<TBLODEV>();
            this.TBLOGRENCİ = new HashSet<TBLOGRENCİ>();
        }
    
        public byte İD { get; set; }
        public string BOLUMU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLODEV> TBLODEV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLOGRENCİ> TBLOGRENCİ { get; set; }
    }
}
