//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDERSHANE.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOGRENCİ
    {
        public int İD { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string SINIFI { get; set; }
        public string CİNSİYETİ { get; set; }
        public string ADRES { get; set; }
        public string POSTAKOD { get; set; }
        public string SEMT { get; set; }
        public string SEHİR { get; set; }
        public string TELEFON { get; set; }
        public string DALI { get; set; }
        public Nullable<byte> BOLUMU { get; set; }
    
        public virtual TBLBOLUM TBLBOLUM { get; set; }
    }
}
