//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDERSHANE.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLODEV
    {
        public int İD { get; set; }
        public string OGRAD { get; set; }
        public string OGRSOYAD { get; set; }
        public string SINIFI { get; set; }
        public Nullable<System.DateTime> VERİLİSTARİH { get; set; }
        public Nullable<System.DateTime> TESLİMTARİH { get; set; }
        public string VERİLENNOT { get; set; }
        public string MAİL { get; set; }
        public Nullable<byte> BOLUMU { get; set; }
        public Nullable<byte> DERS { get; set; }
    
        public virtual TBLBOLUM TBLBOLUM { get; set; }
        public virtual TBLDERS TBLDERS { get; set; }
    }
}
