//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDERSHANE.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLVELİ
    {
        public int İD { get; set; }
        public string AD { get; set; }
        public string SOYAD { get; set; }
        public string YAKINLIK { get; set; }
        public string ADRES { get; set; }
        public string POSTAKOD { get; set; }
        public string TELEFON { get; set; }
        public string TC { get; set; }
        public string GELİRİ { get; set; }
    }
}
